# Learning

Juan Navarro, <jsnavarroa@unal.edu.co>

-------------------------------

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import os

%matplotlib inline

In [2]:
data_path = os.path.abspath("./data")

## 4. SVM training

In [37]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException

chrome_options = webdriver.chrome.options.Options()  
#chrome_options.add_argument("--headless")
prefs = {"download.default_directory" : download_path}
chrome_options.add_experimental_option("prefs",prefs)

browser = webdriver.Chrome(chrome_options=chrome_options)
browser.implicitly_wait(30)

def is_element_present(how, what):
    try: 
        browser.find_element(by=how, value=what)
    except NoSuchElementException as e: 
        return False
    return True

def waitForElementPresent(how, what):
    for i in range(60):
        if is_element_present(how, what): 
                break
        time.sleep(1)

# Get the page
browser.get("https://www.superfinanciera.gov.co/ReporteInformacionFIC/faces/reporte/consultaReporte.xhtml")
# Select the search by name
browser.find_element_by_xpath("//table[@id='formaDatosReporte:tipoBusqueda']/tbody/tr/td[3]/div/div[2]/span").click()
# Wait for name field
waitForElementPresent(By.ID, "formaDatosReporte:nombreEntidadInput_input")
# Write name
browser.find_element_by_id("formaDatosReporte:nombreEntidadInput_input").send_keys("FIDUCIARIA BANCOLOMBIA S.A.")
# Accept the first suggestion
browser.find_element_by_xpath("//div[@id='formaDatosReporte:nombreEntidadInput_panel']/ul/li/span").click()
# Write initial date
browser.find_element_by_id("formaDatosReporte:fechaReporteInicial_input").send_keys("01/01/2018")
# Write final date
browser.find_element_by_id("formaDatosReporte:fechaReporteFinal_input").send_keys("28/05/2018")
# Begin the search
browser.find_element_by_xpath("//button[@id='formaDatosReporte:cmdReporte']/span").click()

while(True):
    # Download report
    browser.find_element_by_xpath("//button[@id='formaResultadoRentabilidad:j_id_1u']/span[2]").click()
    # Go to next report page
    paginator = browser.find_element_by_xpath("//div[@id='formaResultadoRentabilidad:tblResultadoReporte_paginator_bottom']/span[4]")
    paginator.click()
    if "ui-state-disabled" in paginator.get_attribute("class"):
        break
    time.sleep(1)

## 2. Combine all the data in one DataFrame

In [17]:
import pandas as pd
import glob

profitability = pd.DataFrame()

# Go to download path and read all files
retval = os.getcwd()
os.chdir(download_path)
for file in glob.glob("reporteRentabilidades*.xls"):
    print(file)
    df = pd.read_excel(file)
    profitability = profitability.append(df)
    
os.chdir(retval)

profitability.describe(include="all")

reporteRentabilidades (21).xls
reporteRentabilidades (19).xls
reporteRentabilidades (17).xls
reporteRentabilidades (11).xls
reporteRentabilidades (9).xls
reporteRentabilidades (20).xls
reporteRentabilidades3.xls
reporteRentabilidades (16).xls
reporteRentabilidades (14).xls
reporteRentabilidades (12).xls
reporteRentabilidades (2).xls
reporteRentabilidades7.xls
reporteRentabilidades (7).xls
reporteRentabilidades.xls
reporteRentabilidades (22).xls
reporteRentabilidades5.xls
reporteRentabilidades (13).xls
reporteRentabilidades (15).xls
reporteRentabilidades (1).xls
reporteRentabilidades6.xls
reporteRentabilidades (6).xls
reporteRentabilidades (10).xls
reporteRentabilidades4.xls
reporteRentabilidades2.xls
reporteRentabilidades (18).xls
reporteRentabilidades (4).xls
reporteRentabilidades (5).xls
reporteRentabilidades (8).xls
reporteRentabilidades (3).xls

,Fecha corte,Tipo Entidad,Cód. Entidad,Nombre Entidad,Cód. Negocio,Nombre Negocio,Subtipo Negocio,Principal / Compart.,Tipo Part. <sup>1<sup/>,Cons. id Part.,Núm. unidades,Valor unidad para las operaciones del día t,Valor fondo al cierre del día t,Núm. Invers.,Rentab. dia,Rentab. mes,Rentab. sem,Rentab. año
count,72367,72367.0,72367.0,72367,72367.000000,72367,72367,72367,72367.000000,72367.000000,72367,72367,72367,72367.000000,7.236700e+04,72367.000000,72367.000000,72367.000000
unique,502,NaN,NaN,1,NaN,14,2,2,NaN,NaN,3988,8769,8907,NaN,NaN,NaN,NaN,NaN
top,01/05/2018,NaN,NaN,Fiduciaria Bancolombia S.A.,NaN,FONDO DE INVERSION COLECTIVA ABIERTO CON PACTO...,FIC DE TIPO GENERAL,Principal,NaN,NaN,"3,275,033.763",$0.00,$0.00,NaN,NaN,NaN,NaN,NaN
freq,551,NaN,NaN,72367,NaN,19440,42768,64591,NaN,NaN,1956,1809,1823,NaN,NaN,NaN,NaN,NaN
mean,NaN,5.0,31.0,NaN,13638.438183,NaN,NaN,NaN,7.032929,1.020797,NaN,NaN,NaN,45668.029475,4.341376e+19,265.039498,6.016400,4.499958
std,NaN,0.0,0.0,NaN,19417.252097,NaN,NaN,NaN,1.402146,1.495092,NaN,NaN,NaN,127242.047306,4.401666e+21,4896.790070,20.104517,13.955301
min,NaN,5.0,31.0,NaN,2713.000000,NaN,NaN,NaN,5.000000,0.000000,NaN,NaN,NaN,0.000000,-1.000000e+02,-100.000000,-100.000000,-100.000000
25%,NaN,5.0,31.0,NaN,2971.000000,NaN,NaN,NaN,5.000000,0.000000,NaN,NaN,NaN,11.000000,-1.292288e+00,0.000000,0.119185,1.466777
50%,NaN,5.0,31.0,NaN,3644.000000,NaN,NaN,NaN,8.000000,0.000000,NaN,NaN,NaN,922.000000,2.409070e+00,5.246031,5.888318,7.105770
75%,NaN,5.0,31.0,NaN,14173.000000,NaN,NaN,NaN,8.000000,2.000000,NaN,NaN,NaN,3416.000000,6.307102e+00,8.193112,9.143686,9.161224
max,NaN,5.0,31.0,NaN,69940.000000,NaN,NaN,NaN,8.000000,5.000000,NaN,NaN,NaN,508931.000000,4.475636e+23,120891.484000,243.611420,84.637510

## 3. Preprocessing

In [26]:
profitability = profitability.drop_duplicates()

# Drop columns
profitability = profitability. drop(columns=['Tipo Entidad'], errors='ignore')

# Convert dates
profitability['Fecha corte'] = pd.to_datetime(profitability['Fecha corte'],infer_datetime_format=False)
profitability = profitability.sort_values(by=['Fecha corte']) 

profitability.to_excel(download_path+"/profitability.xls", index=False)

profitability.describe(include="all")

,Fecha corte,Cód. Entidad,Nombre Entidad,Cód. Negocio,Nombre Negocio,Subtipo Negocio,Principal / Compart.,Tipo Part. <sup>1<sup/>,Cons. id Part.,Núm. unidades,Valor unidad para las operaciones del día t,Valor fondo al cierre del día t,Núm. Invers.,Rentab. dia,Rentab. mes,Rentab. sem,Rentab. año
count,9367,9367.0,9367,9367.000000,9367,9367,9367,9367.000000,9367.000000,9367,9367,9367,9367.000000,9.367000e+03,9367.000000,9367.000000,9367.000000
unique,502,NaN,1,NaN,14,2,2,NaN,NaN,3988,8769,8907,NaN,NaN,NaN,NaN,NaN
top,2017-12-14 00:00:00,NaN,Fiduciaria Bancolombia S.A.,NaN,FONDO DE INVERSION COLECTIVA ABIERTO CON PACTO...,FIC DE TIPO GENERAL,Principal,NaN,NaN,0,$0.00,$0.00,NaN,NaN,NaN,NaN,NaN
freq,19,NaN,9367,NaN,2510,5522,8363,NaN,NaN,252,249,251,NaN,NaN,NaN,NaN,NaN
first,2017-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
last,2018-12-05 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,31.0,NaN,13602.600619,NaN,NaN,NaN,7.035337,1.018256,NaN,NaN,NaN,45127.343333,4.791477e+19,292.815960,6.348144,4.648079
std,NaN,0.0,NaN,19281.443329,NaN,NaN,NaN,1.401294,1.494165,NaN,NaN,NaN,125847.115228,4.624407e+21,5143.805785,20.628994,14.075846
min,NaN,31.0,NaN,2713.000000,NaN,NaN,NaN,5.000000,0.000000,NaN,NaN,NaN,0.000000,-1.000000e+02,-100.000000,-100.000000,-100.000000
25%,NaN,31.0,NaN,2971.000000,NaN,NaN,NaN,5.000000,0.000000,NaN,NaN,NaN,11.000000,-1.233254e+00,-0.035499,0.554810,1.342334
50%,NaN,31.0,NaN,3644.000000,NaN,NaN,NaN,8.000000,0.000000,NaN,NaN,NaN,868.000000,2.659741e+00,5.314435,6.017748,7.382078
75%,NaN,31.0,NaN,14173.000000,NaN,NaN,NaN,8.000000,2.000000,NaN,NaN,NaN,3254.000000,6.526406e+00,8.553478,9.224975,9.216057
max,NaN,31.0,NaN,69940.000000,NaN,NaN,NaN,8.000000,5.000000,NaN,NaN,NaN,508931.000000,4.475636e+23,120891.484000,243.611420,84.637510